name: MkDocs Build + Deploy

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions

    - name: Build MkDocs
      run: mkdocs build --clean

    - name: Create and force push to documentation branch
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        # git branch --delete production
        git checkout -b production  # Replace 'documentation' with the desired branch name
        # git checkout production
        find . -type f ! -path './site*' ! -path './.*' -exec echo {} +
        find . -type f ! -path './site*' ! -path './.*' -exec rm -f {} +
        rm -rf docs 
        mv site docs
        touch .nojekyll
        git add .
        git commit -m "Content update"
        git push --force origin production
